### ISSUE TITLE
Use of the library causes an error on iOS

### ISSUE THREAD

**Issue by zakalwe314** [tidal-engineering/ie11-scroll-into-view#1]
We have an cross-browser webapp and we had a problem with ie which your project sorted (thank you).  
Unfortunately on iOS we get: "SyntaxError: Strict mode does not allow function declarations in a lexically nested statement" and the app does not run.

**Comment by zalkawe314** [comment]
BTW I'm looking to see if I can fix it and I'll submit a pull request if I can.

**Comment by eirslett** [comment]
Could you try commenting out line 15? Which is the `use strict` line?

**Comment by eirslett** [comment]
Or maybe refactor the `hasScroller` stuff, so that it's not wrapped in an anonymous function, that could be the problem maybe.

**Comment by zalkawe314** [comment]
I'm trying the second option - I'd noticed your comment about eslint and wonderred if that could be to do with it.

**Comment by zalkawe314** [comment]
That work (refactoring hasScroller that is, and removing the function declarations from the ternary expression).

I've also fixed (or at least changed) a second bug in the process.  The description is a little long, would you prefer I raise a second issue, or just describe it here?

(now I just need to figure out how to do the pull request thing - been coding for (too many) years but new to github)

**Comment by eirslett** [comment]
You can make a PR, which will also become a new, separate girhub issue, and describe it there. Good luck ;-)
